# [depts] specific values for migration playbook.
# https://github.com/SU-SWS/ansible-playbooks
# ===============================================
#
# These values will be used when Ansible runs the migration playbook
# against hosts listed under the [depts] inventory group.
#
# Enter the server from which we should pull the live site's database and
# and files. Unless the sites are people sites, we'll probably want to
# pull copies from `sites2`.
server: "sites2"
#
# We'll be using drush aliases to download the live site's database and
# files. Enter the alias we should be using for sites in this group. Unless
# the sites are people sites, we'll probably want to use `sse`. People sites
# should use `ppl`.
server_alias: "sse"
#
# We had a convention on Stanford Sites of prefixing sitenames with `dp` for
# people sites and `ds` for other types of sites. Enter which prefix we should
# use for this in this group.
site_prefix: "ds"
#
# Jumpstart product flag. Set this to true to have the script automagically
# find and set the installation profile variable.
product_site: "TRUE"
#
# ace_environment
#
#ace_environment: ""
#
# ignore_updb_errors
#
ignore_updb_errors: "TRUE"
