# [all] specific values for migration playbook.
# https://github.com/SU-SWS/ansible-playbooks
# =============================================
#
# These values will be used when Ansible runs the migration playbook
# against all hosts.
#
# Enter the profile you would like Site Factory to install initially, when
# creating the site. Note, this value is kind of irrelevant because all
# Site Factory sites on the same stack run off the same codebase.  And which
# profile a site uses will be saved in the database we load from production.
# So there's not point in waiting for `stanford_sites_jumpstart_academic` to
# install before blowing away that database.
profile: "testing"
#
# We are only migrating Drupal 7 sites, so we will only be migrating sites
# to the `cardinald7` stack.
stack: "cardinald7"
#
# The Site Factory API requires that we pass it the stack ID. The `cardinalsites`
# stack is ID: `2` and `cardinald7` stack is ID: `1`.
stack_id: "2"
#
# These variables (sitefactory_environment, stanford_environment, and
# drush_environment) should be set to empty strings as defaults, in order to
# avoid "undefined variable" error messages. They are set to appropriate values,
# if needed, in get-sitename/tasks/main.yml.
sitefactory_environment: ""
stanford_environment: ""
drush_environment: ""

# This variable (ignore_updb_errors) should be set to an empty string by
# default, in order to avoid "undefined variable" error messages. It can be
# set on a per-site basis to "TRUE" in the inventory file. It is case-sensitive.
ignore_updb_errors: ""

# If you have something different than ds_ or dp_
sites_drush_alias: "default"
