# [all] specific values for migration playbook.
# https://github.com/SU-SWS/ansible-playbooks
# =============================================
#
# These values will be used when Ansible runs the migration playbook
# against all hosts.
#
# Release of ansible-playbooks used to migrate sites to production.  We
# hope never to re-migrate a site once it's been launched in ACSF.  That
# said, should we discover problems with a particular version or
# versions of the script, this variable will give us the option to find
# and re-migrate only those affected sites.
migration_version: "master"
#
# Enter the profile you would like Site Factory to install initially, when
# creating the site. Note, this value is kind of irrelevant because all
# Site Factory sites on the same stack run off the same codebase.  And which
# profile a site uses will be saved in the database we load from production.
# So there's not point in waiting for `stanford_sites_jumpstart_academic` to
# install before blowing away that database.
profile: "testing"
#
# These variables (sitefactory_environment, stanford_environment, and
# drush_environment) should be set to empty strings as defaults, in order to
# avoid "undefined variable" error messages. They are set to appropriate values,
# if needed, in get-sitename/tasks/main.yml.
sitefactory_environment: ""
stanford_environment: ""
drush_environment: ""

# This variable (ignore_updb_errors) should be set to an empty string by
# default, in order to avoid "undefined variable" error messages. It can be
# set on a per-site basis to "TRUE" in the inventory file. It is case-sensitive.
ignore_updb_errors: "TRUE"

# Set site_exists to FALSE initially to avoid undefined variable errors. See
# roles/setup-site/tasks/main.yml.
site_exists: "FALSE"

# Set enable_maintenance_mode_source to FALSE initially, to avoid undefined
# variable errors. It can be overridden in migration_vars.yml
enable_maintenance_mode_source: "FALSE"

# Set disable_maintenance_mode_dest to TRUE initially, to avoid undefined
# variable errors. It can be overridden in migration_vars.yml
disable_maintenance_mode_dest: "FALSE"

# This is a little-used variable; only used when there are file permissions
# issues from files that were not created/saved by Drupal.
chmod: "FALSE"

# Set run_sarl="FALSE" in migration_vars.yml or on a per-host basis in an
# inventory to skip the steps that strip absolute paths in menus and links.
# Use case: URLs in links and menus that link to anchors or fragments.
# See roles/change-paths/tasks/main.yml, the "Remove absolute paths for links
# and menus" and "Remove absolute vhost paths for links and menus" tasks.
run_sarl: "TRUE"

# stanford_jumpstart_shortcuts defines permissions to allow access to "top
# reports" menu items ("Recent log messages", "Top 'access denied' errors",
# "Top 'page not found' errors", and "Top search phrases"). It also places
# these items in the Site Actions menu. To disable (not delete) these items
# from the Site Actions menu, set disable_top_reports_menu_items: "TRUE"
# in migration_vars.yml or in an inventory file.
disable_top_reports_menu_items: "FALSE"
