# [groups] specific values for migration playbook.
# https://github.com/SU-SWS/drupal-caravan
# ==================================================
#
# These values will be used when Ansible runs the migration playbook
# against hosts listed under the [groups] inventory group.
#
# Enter the Site Factory Group ID or ID's within which this site should
# appear in the Site Factory dashboard.
# Example: "126,127" or "126"
group_ids: 126
#
# Enter the server from which we should pull the live site's database and
# and files. Unless the sites are people sites, we'll probably want to
# pull copies from `sites2`.
server: "sites2"
#
# We'll be using drush aliases to download the live site's database and
# files. Enter the alias we should be using for sites in this group. Unless
# the sites are people sites, we'll probably want to use `sse`. People sites
# should use `ppl`.
server_alias: "sse"
#
# We had a convention on Stanford Sites of prefixing sitenames with `dp` for
# people sites and `ds` for other types of sites. Enter which prefix we should
# use for this in this group.
site_prefix: "ds"
#
# Department sites get extra treatment during the migration process. There shouldn't
# be any department sites in the [groups] group, so this value should be set to FALSE.
dept_site: "FALSE"
