# [depts] specific values for migration playbook.
# https://github.com/SU-SWS/ansible-playbooks
# ===============================================
#
# These values will be used when Ansible runs the migration playbook
# against hosts listed under the [depts] inventory group.
#
# Enter the server from which we should pull the live site's database and
# and files. Unless the sites are people sites, we'll probably want to
# pull copies from `sites2`.
server: "sites2"
#
# We'll be using drush aliases to download the live site's database and
# files. Enter the alias we should be using for sites in this group. Unless
# the sites are people sites, we'll probably want to use `sse`. People sites
# should use `ppl`.
server_alias: "sse"
#
# We had a convention on Stanford Sites of prefixing sitenames with `dp` for
# people sites and `ds` for other types of sites. Enter which prefix we should
# use for this in this group.
site_prefix: "ds"
#
# Department sites get extra treatment during the migration process. Help us
# skip this for non-department sites, by setting this value to FALSE.
dept_site: "FALSE"
#
# Jumpstart product flag. Set this to true to have the script automagically
# find and set the installation profile variable.
product_site: "TRUE"
#
# The Site Factory API requires that we pass it the stack ID.
# The "cardinalsites" (Drupal 8) stack ID is 1.
# The "cardinald7" (Drupal 7, groups and depts) stack ID is 2.
# The "leland" (Drupal 7, people) stack ID is 3.
stack_id: "2"
#
# Drupal 7 product sites go on the `cardinald7` stack.
stack: "cardinald7"

# Some profiles have modules in the "modules" directory and the "Find and set
# the install profile by helper modules" task in the post-db-restore role will
# fail with a "cannot redeclare" fatal error.
# Set duplicate_code_in_profile: "TRUE" in migration_vars.yml or on a per-host
# basis in the inventory to rebuild the registry during this task.
duplicate_code_in_profile: "FALSE"
