---
# Ansible role for preparing site names for use with ACSF environments and drush.
# https://github.com/SU-SWS/ansible-playbooks
# ===========================================================
#
# The purpose of this role is to take the sitename from sites.stanford.edu or
# people.stanford.edu, sanitize it for the ACSF environment, and create various
# tokens from it for use on ACSF and drush.
#
# INPUTS:
#   ace_environment
#   acquia_username
#   acquia_api_key
#   inventory_hostname
#   site_prefix
#
# OUTPUTS:
#   ace_site_name
#   drush_environment
#   sites_service
#   site_environment
#   stanford_environment
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# Ex: sites
# Ex: people
- name: Set sites_service variable
  set_fact:
    sites_service: "sites"

# Ex. My-Awesome-Website becomes myawesomewebsite
- name: Sanitize inventory_hostname
  set_fact:
    ace_site_name: "{{ inventory_hostname | lower | regex_replace('[^a-z0-9]') }}"
    cacheable: TRUE

- name: Debug ACE site name
  debug:
    var: ace_site_name
  when: print_debug_messages == "TRUE"

# Ex. "myaweseomwebsite-" when the environment is DEV or TEST
- name: Create token for site environment URL
  set_fact:
    site_environment: "{{ ace_environment }}-"
    cacheable: TRUE
  when:
    ace_environment != ""

# Ex. "-dev" or "-test" for DEV or TEST, respectively
- name: Create token for stanford.edu environment URL
  set_fact:
    stanford_environment: "-{{ ace_environment }}"
    cacheable: TRUE
  when:
    ace_environment != ""

# Ex. ".dev" or ".test" for DEV or TEST, respectively
- name: Create token for drush environment
  set_fact:
    drush_environment: ".{{ ace_environment }}"
    cacheable: TRUE
  when:
    ace_environment != ""
