---
# Ansible role for checking whether a site is in the Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ===========================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state
# in which acsf_site_name, drush_environment, sites_service,
# sitefactory_environment, and stanford_environment have values.
#
# INPUTS:
#   inventory_hostname
#   acsf_environment
#   acquia_username
#   acquia_api_key
#
# OUTPUTS:
#   acsf_site_name
#   drush_environment
#   sites_service
#   sitefactory_environment
#   stanford_environment
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# Ex: sites
# Ex: people
- name: Set sites_service variable
  set_fact:
    sites_service: "{% if site_prefix=='dp' %}people{% elif site_prefix=='ds'%}sites{% endif %}"

- name: Sanitize inventory_hostname
  set_fact:
    acsf_site_name: "{{ inventory_hostname | lower | regex_replace('[^a-z0-9]') }}"
    cacheable: TRUE

- name: ACSF site name
  debug:
    var: acsf_site_name
  when: print_debug_messages == "TRUE"

- name: Create token for Site Factory environment URL
  set_fact:
    sitefactory_environment: "{{ acsf_environment }}-"
    cacheable: TRUE
  when:
    acsf_environment != ""

- name: Create token for stanford.edu environment URL
  set_fact:
    stanford_environment: "-{{ acsf_environment }}"
    cacheable: TRUE
  when:
    acsf_environment != ""

- name: Create token for drush environment
  set_fact:
    drush_environment: ".{{ acsf_environment }}"
    cacheable: TRUE
  when:
    acsf_environment != ""
