---
# Ansible role for preparing site names for use with ACSF environments and drush.
# https://github.com/SU-SWS/ansible-playbooks
# ===========================================================
#
# The purpose of this role is to take the sitename from sites.stanford.edu or
# people.stanford.edu, sanitize it for the ACSF environment, and create various
# tokens from it for use on ACSF and drush.
#
# INPUTS:
#   acsf_environment
#   acquia_username
#   acquia_api_key
#   inventory_hostname
#   site_prefix
#
# OUTPUTS:
#   acsf_site_name
#   drush_environment
#   sites_service
#   sitefactory_environment
#   stanford_environment
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# Ex: sites
# Ex: people
- name: Set sites_service variable
  set_fact:
    sites_service: "{% if site_prefix=='dp' %}people{% elif site_prefix=='ds'%}sites{% endif %}"

# Ex. My-Awesome-Website becomes myawesomewebsite
- name: Sanitize inventory_hostname
  set_fact:
    acsf_site_name: "{{ inventory_hostname | lower | regex_replace('[^a-z0-9]') }}"
    cacheable: TRUE

- name: Debug ACSF site name
  debug:
    var: acsf_site_name
  when: print_debug_messages == "TRUE"

# Ex. "myaweseomwebsite-" when the environment is DEV or TEST
- name: Create token for Site Factory environment URL
  set_fact:
    sitefactory_environment: "{{ acsf_environment }}-"
    cacheable: TRUE
  when:
    acsf_environment != ""

# Ex. "-dev" or "-test" for DEV or TEST, respectively
- name: Create token for stanford.edu environment URL
  set_fact:
    stanford_environment: "-{{ acsf_environment }}"
    cacheable: TRUE
  when:
    acsf_environment != ""

# Ex. ".dev" or ".test" for DEV or TEST, respectively
- name: Create token for drush environment
  set_fact:
    drush_environment: ".{{ acsf_environment }}"
    cacheable: TRUE
  when:
    acsf_environment != ""
