---
# Ansible playbook that recreates in Site Factory sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will create a new site in Acquia Cloud Site Factory, and
# then sync a site from the SWS legacy hosting platform to the newly created
# site.
#
# Can be run with: ansible-playbook -i inventory/sites migration-playbook.yml
#
# RE-STARTING:
# If you need to restart the site-migration process, restart from the top.
# --start-at-task="" does not always run dependencies nor grab variables
# required for a role.
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Migrate sites from SWS infrastructure to Site Factory
# =============================================================
- hosts: groups,depts,people
  connection: local

  vars_files:
    - migration_vars.yml
    - ansible-sync/prod-sites.yml

  roles:
    - { role: protect-prod }
    - { role: setup-local }
    - { role: download-site }
    - { role: css-injector }
    - { role: check-php }
    - { role: setup-site }
    - { role: upload-site }
    - { role: change-paths }
    - { role: add-vhost }
    - { role: cleanup-local }
  serial: 12
