---
# Ansible playbook that recreates in Site Factory sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will sync a site from the Stanford Sites legacy hosting platform
# to its destination on ACSF.
#
# Can be run with: ansible-playbook -i inventory/sites migration-sync-only-playbook.yml
#
# SEE ALSO:
#
# full-migration-playbook.yml to create a new site on ACSF and sync from the
# existing infrastructure.
#
# acsf-site-setup-playbook.yml to only run the roles that set up the site on
# ACSF.
#
# add-vhost-playbook.yml if you wish only to add a vhost as a custom domain.
#
# post-db-restore-playbook.yml to only run the tasks that happen after the ACSF
# site has been restored from the database dump.
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Migrate sites from SWS infrastructure to Site Factory
# =============================================================
- hosts: groups,depts,people,products
  connection: local

  vars_files:
    - migration_vars.yml
    - ansible-sync/prod-sites.yml

  roles:
    - { role: setup-local }
    - { role: download-site }
    - { role: css-injector }
    - { role: upload-site }
    - { role: post-db-restore }
    - { role: change-paths }
    - { role: acsf-optimizations }
    - { role: cleanup-local }
  serial: 12
