---
# Ansible playbook that recreates in Site Factory sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will create a new site in Acquia Cloud Site Factory, and
# then sync a site from the SWS legacy hosting platform to the newly created
# site.
#
# Can be run with: ansible-playbook -i inventory/sites migration-playbook.yml
#
# RE-STARTING:
# If you need to restart the site-migration process, use --tags "" instead of
# --start-at-task="". Tags allow us to re-start at a safe place in the
# playbook and rely on dependencies to grab variables required for a role.
#
# Example:
# ansible-playbook -i inventory/sites migration-playbook.yml --tags "download-site"
#
# Re-running this playbook with the "download-site" tag, will run download-site,
# get-sitename (because get-sitename is a dependency of upload-site), then
# upload-site.
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Migrate sites from SWS infrastructure to Site Factory
# =============================================================
- hosts: groups,depts,people
  connection: local

  vars_files:
    - migration_vars.yml

  roles:
    - { role: setup-local }
    - { role: download-site, tags: [download-site] }
    - { role: check-php, tags: [check-php,download-site] }
    - { role: setup-site, tags: [download-site,check-php] }
    - { role: upload-site, tags: [upload-site,setup-site,download-site,check-php] }
    - { role: get-sitename, tags: [upload-site,setup-site,download-site,check-php] }
    - { role: add-vhost, tags: [add-vhost,upload-site,setup-site,download-site,check-php] }
    - { role: cleanup-local, tags: [cleanup-local,upload-site,setup-site,download-site,check-php] }
  serial: 12
