---
# Ansible playbook that recreates in Site Factory sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will customize our servers on Acquia Cloud Site Factory with
# drush plugins and preferences that we define.
#
# Can be run with:
# ansible-playbook -i inventory/servers server-settings-playbook.yml
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Set up server customizations
# ====================================
# - hosts: dev,test,prod
- hosts: dev
#  connection: local

  vars_files:
    - server_vars.yml

  roles:
    - setup-server
