---
# Ansible role for creating a site on ACE.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a vhost for a site in ACE.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   new_absolute_path
#   site_id
#   site_environment
#   sites_service
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Add sites-pro environment domain
  shell: "{{ drush_alias }} ac-domain-add {{ inventory_hostname }}{{ stanford_environment }}.sites-pro.stanford.edu"

# We only do this for production sites with vhosts.
# - name: Add custom domain
#   shell: "drush @stanfordpro.prod ac-domain-add {{ new_absolute_path }}"
#   when: new_absolute_path !== ""
