---
# Ansible role for creating a site on ACE.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a vhost for a site in ACE.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   new_absolute_path
#   site_id
#   site_environment
#   sites_service
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Debug new_absolute_path
  debug:
    var: new_absolute_path
  when: print_debug_messages == "TRUE"

- name: Check if inventory_hostname.sites-pro.stanford.edu exists as a custom domain
  shell: "{{ drush_alias }} ac-domain-info {{ inventory_hostname | lower | regex_replace('[^a-z0-9-]') }}{{ stanford_environment }}.sites-pro.stanford.edu"
  register: inventory_hostname_exists_check
  ignore_errors: "yes"

# Add the inventory_hostname as a custom domain.
# This will cause a fail if the vhost already exists. Make it dependent on the
# custom domain not existing.
# Ex. jumpstart-sws-services.sites-pro.stanford.edu
- name: Add inventory_hostname as sites-pro environment domain
  shell: "{{ drush_alias }} ac-domain-add {{ inventory_hostname | lower | regex_replace('[^a-z0-9-]') }}{{ stanford_environment }}.sites-pro.stanford.edu"
  when: inventory_hostname_exists_check.stdout is search('Resource not found')

- name: Check if vhost.sites-pro.stanford.edu exists as a custom domain
  shell: "{{ drush_alias }} ac-domain-info {{ vhost }}{{ stanford_environment }}.sites-pro.stanford.edu"
  register: vhost_sitespro_custom_domain_exists_check
  ignore_errors: "yes"

# Add the vhost as a custom domain.
# This will cause a fail if the vhost already exists. Make it dependent on the
# custom domain not existing.
# Ex. sites-jumpstart.sites-pro.stanford.edu
- name: Add vhost as sites-pro environment domain
  shell: "{{ drush_alias }} ac-domain-add {{ vhost }}{{ stanford_environment }}.sites-pro.stanford.edu"
  when: vhost_sitespro_custom_domain_exists_check.stdout is search('Resource not found')

- name: Check if vhost.stanford.edu exists as a custom domain
  shell: "{{ drush_alias }} ac-domain-info {{ vhost }}{{ stanford_environment }}.sites-pro.stanford.edu"
  register: vhost_custom_domain_exists_check
  ignore_errors: "yes"


# We only do this for production sites with vhosts.
- name: Add vhost as custom domain
  shell: "drush @stanfordpro.prod ac-domain-add {{ new_absolute_path }}"
  when: new_absolute_path != "" and launch_tasks == "launch" and vhost_custom_domain_exists_check.stdout is search('Resource not found')

# Force loading through the canonical URL by setting the
# "stanfordpro_helper_canonical_url" variable to (e.g.) "foo.stanford.edu". This
# will only take affect on sites on the prod environment, because the
# stanfordpro_helper module restricts that functionality to prod
- name: Set stanfordpro_helper_canonical_url variable prior to launch
  shell: "{{ drush_alias }} -y --exact vset stanfordpro_helper_canonical_url {{ new_absolute_path }}"
  when: launch_tasks == "launch"
