---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a vhost for a site in Site Factory.
#
# INPUTS:
#   acsf_site_name
#   sitefactory_environment
#   stanford_environment
#   acquia_username
#   acquia_api_key
#   existing_sites
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Establish numerical id from existing_sites JSON response
  set_fact:
    site_id: "{{ existing_sites | json_query(existing_sites_query) }}"
  vars:
    existing_sites_query: "json.sites[?site=='{{ acsf_site_name }}'] | [0].id"

#- name: Debug json formatting on sites_created id
#  debug:
#    var: site_id

- name: Add vhost as domain
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/domains/{{ site_id }}/add"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    body:
      domain_name: "{{ vhost }}.stanford.edu"
  when:
    vhost is defined

- name: Add inventory_hostname as domain
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/domains/{{ site_id }}/add"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    body:
      domain_name: "{{ inventory_hostname }}{{ stanford_environment }}.cardinalsites.stanford.edu"
    return_content: yes
    register: inventory_hostname_domain_response
  when:
    inventory_hostname != acsf_site_name
