---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a vhost for a site in Site Factory.
#
# INPUTS:
#   acsf_site_name
#   sitefactory_environment
#   acquia_username
#   acquia_api_key
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Add vhost as domain
  uri:
    url: "https://www.{{ sitefactory_environment }}.acsitefactory.com/api/v1/domains/{{ item }}/add"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    body:
      domain_name: "{{ vhost }}.stanford.edu"
  with_items: "{{ existing_sites | json_query(\"json.sites[?site=='\" + acsf_site_name + \"'].id\") }}"
  when:
    vhost is defined

# Waiting to find out via Acquia ticket #624799 if this is possible
# - name: Add inventory_hostname as domain
#   uri:
#     url: "https://www.{{ sitefactory_environment }}.acsitefactory.com/api/v1/domains/{{ item }}/add"
#     method: POST
#     user: "{{ acquia_username }}"
#     password: "{{ acquia_api_key }}"
#     force_basic_auth: yes
#     body_format: json
#     body:
#       domain_name: "{{ inventory_hostname }}.{{ sitefactory_environment }}.acsitefactory.com"
#     return_content: yes
#   register: inventory_hostname_domain_response
#   with_items: "{{ existing_sites | json_query(\"json.sites[?site=='\" + acsf_site_name + \"'].id\") }}"
