---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a vhost for a site in Site Factory.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   new_absolute_path
#   site_id
#   sitefactory_environment
#   sites_service
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Debug new_absolute_path
  debug:
    var: new_absolute_path
  when: print_debug_messages == "TRUE" and sites_service == "sites"

# We only do this for group/dept sites. People sites get automagic hostnames.
- name: Add custom domain
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/domains/{{ site_id }}/add"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    body:
      domain_name: "{{ new_absolute_path }}"
  when: sites_service == "sites"

# Ex. drupal7-update-status.sites.stanford.edu.
- name: Add inventory_hostname as domain
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/domains/{{ site_id }}/add"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    body:
      domain_name: "{{ inventory_hostname }}{{ stanford_environment }}.{{ sites_service }}.stanford.edu"
    return_content: yes
    register: inventory_hostname_domain_response
  when: inventory_hostname != acsf_site_name and sites_service == "sites"

# Force loading through the canonical URL by setting the
# "acsf_helper_canonical_url" variable to (e.g.) "foo.stanford.edu". This will
# only take affect on sites on the prod environment, because the acsf_helper
# module restricts that functionality to prod
- name: Set acsf_helper_canonical_url variable prior to launch
  shell: "{{ drush_alias }} -y --exact vset acsf_helper_canonical_url {{ new_absolute_path }}"
  when: launch_tasks == "launch" and set_acsf_helper_canonical_url == "TRUE"
