---
# Ansible role for uploading the database and files to Enterprise.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role uploads the database and files from local to Enterprise. It also
# runs a number of tasks to transform the database in such a way that images
# and absolute paths will work in the new ACSF environment. If any part of this
# role fails for a site, start from the top with a fresh download of the site.
#
# INPUTS:
#   ace_site_name
#   inventory_hostname
#   site_environment
#   drush_alias
#   drush_environment
#   stack
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Get current install profile
  shell: "{{ drush_alias }} ev 'echo variable_get(\"install_profile\", \"set_me\");'"
  register: get_profile_output

- name: Set install_profile ansible var
  set_fact:
    install_profile: "{{ get_profile_output.stdout }}"

# Set the installation profile if one does not exist.
- name: Find and set default install profile to stanford
  shell: "{{ drush_alias }} vset install_profile stanford"
  when: install_profile == "set_me" and dept_site == "FALSE" and product_site == "FALSE"

# Set the install profile by looking for the enabled supporting module.
# Order of operations is important here, because a JSA site may have BOTH
# "stanford_jumpstart" and "stanford_jumpstart_academic" enabled, yet we want
# to be sure to set "install_profile" to "stanford_sites_jumpstart_academic" for
# JSA sites (so that they get all the correct code).
- name: Find and set the install profile by helper modules.
  shell: "FOUND=$({{ drush_alias }} php-eval \"var_dump(module_exists('{{ item.module }}'));\"); if [[ \"$FOUND\" =~ 'true' ]]; then {{ drush_alias }} -y vset install_profile '{{ item.profile }}'; {{ drush_alias }} -y sqlq 'update system set status=\"1\" where name=\"{{ item.profile }}\"'; {{ drush_alias }} -y sqlq 'update system set status=\"0\" where name=\"stanford\"'; {{ drush_alias }} rr; {{ drush_alias }} -y en stanford_jumpstart_shortcuts stanford_jumpstart_site_actions; fi;"
  with_items:
    - { module: 'stanford_jumpstart', profile: 'stanford_sites_jumpstart' }
    - { module: 'stanford_jumpstart_plus', profile: 'stanford_sites_jumpstart_plus' }
    - { module: 'stanford_jumpstart_academic', profile: 'stanford_sites_jumpstart_academic' }
    - { module: 'stanford_jumpstart_vpsa', profile: 'stanford_sites_jumpstart_vpsa' }
    - { module: 'stanford_jumpstart_lab', profile: 'stanford_sites_jumpstart_lab' }
    - { module: 'stanford_jumpstart_engineering', profile: 'stanford_sites_jumpstart_engineering' }
  when: product_site == "TRUE"

- name: Do post-database-restore tasks
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y dis simplesamlphp_auth"
    - "-y pm-uninstall simplesamlphp_auth"
    - "-y en acquia_agent acquia_purge_d8cache acquia_spi stanfordpro_helper stanford_simplesamlphp_auth stanford_ssp paranoia syslog"
    - 'ev "_paranoia_remove_risky_permissions();"'
    - "-y --exact vset sws_migration_version {{ migration_version }}"
    - "-y --exact vset stanford_ssp_role_map_source workgroup"
    - "-y --exact vset stanford_ssp_workgroup_api_cert {{ certs_dir }}stanford_ssp.cert"
    - "-y --exact vset stanford_ssp_workgroup_api_key {{ certs_dir }}stanford_ssp.key"
    - "-y --exact vset stanford_ssp_role_map_source workgroup"
    - "-y --exact vset stanford_simplesamlphp_auth_installdir {{ saml_dir }}"
    - "-y dis anchorage_helper dblog stanford_afs_quota openid mailsystem mollom s3fs smtp stanford_s3fs_if statistics xmlrpc"
    - "-y pm-uninstall anchorage_helper mailsystem smtp stanford_afs_quota mollom openid stanford_s3fs_if statistics xmlrpc"
    - "-y pm-uninstall s3fs"
    - "-y --exact vdel mail_system"
    # WMD actions not needed for Cardinal at Work.
    # Must truncate this table otherwise users will lose roles in WMD->SSP upgrade path.
    # - "sqlq 'truncate table webauth_roles_history'"
    # - "sspwmd"
    #- "-y pm-uninstall webauth_extras"
  notify: Clear site cache
  ignore_errors: "yes"

- name: Enable Stanford SAML Login Block module
  shell: "{{ drush_alias }} -y en stanford_saml_block"
  when: enable_stanford_saml_block == "TRUE"

# Rebuild permissions. This resolves the "The content access permissions need
# to be rebuilt" message. NOTE: this is a slow task, so only run this as
# needed on a per-host basis
- name: Rebuild content permissions
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - 'php-eval "node_access_rebuild();"'
  when: rebuild_permissions == "TRUE"
  notify: Clear site cache

- name: Post-database-restore tasks if not launch
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y en nobots"
    - "-y dis googleanalytics pingdom_rum"
    - "sqlq 'update search_api_index set read_only=\"1\"'"
  when: launch_tasks != "launch"
  notify: Clear site cache

# Copy public files so that they exist and Drupal can find them if needed
- name: Copy public files from local to Enterprise
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/s3fs-public/ @stanfordhr{{ drush_environment }}.{{ inventory_hostname }}:%files/ --exclude-paths=sites/default/files/js_injector/"
  notify: Clear site cache

# Copy private files so that they exist and Drupal can find them if needed
- name: Copy private files from local to Enterprise
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/s3fs-private/ @stanfordhr{{ drush_environment }}.{{ inventory_hostname }}:%private/"
  notify: Clear site cache

- name: Generate random password
# See https://stackoverflow.com/a/45080709
  set_fact:
    random_pw: "{{ 999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N')) | to_uuid() }}"

- name: Debug random password
  debug:
    var: random_pw
  when: print_debug_messages == "TRUE"

- name: Randomize User 1 password
  shell: "{{ drush_alias }} user-password 1 --password=\"{{ random_pw }}\""
