---
# Ansible role for setting up localhost to accomodate migration.
# https://github.com/SU-SWS/ansible-playbooks
# =============================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state of
# a directory on locahost, where we can temporarily sync a site database and files.
#
# INPUTS:
#   inventory_hostname
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --
#
- name: Create inventory_hostname directory in tmp
  file:
    path: "/tmp/{{ inventory_hostname }}"
    state: directory
    mode: 0755

- name: Create inventory_hostname/files directory in tmp
  file:
    path: "/tmp/{{ inventory_hostname }}/files"
    state: directory
    mode: 0755

- name: Update drush aliases
  template:
    src: "stanfordpro.aliases.drushrc.php"
    dest: "~/.drush/stanfordpro.aliases.drushrc.php"
