---
# Ansible role for setting a number of variables (mostly paths and URLs).
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role is required for "change-paths", "css-injector", "setup-site",
#   and "upload-site".
#
# INPUTS:
#   acsf_environment
#   acsf_site_name
#   drush_environment
#   inventory_hostname
#   launch_tasks
#   site_prefix
#   stack
#   stack_id
#   vhost
#
# OUTPUTS:
#   absolute_path_launch
#   absolute_path_prod
#   absolute_path_sites_service
#   absolute_path_testing
#   absolute_vhost_path_sites_service
#   drush_alias
#   file_public_path
#   new_absolute_path
#   scripts_dir
#   sites_service
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# Ex. /var/www/html/cardinald7.02live/scripts
# Ex. /var/www/html/cardinald7.02test/scripts
# Ex. /var/www/html/cardinald7.02dev/scripts
- name: Set scripts_dir variable
  set_fact:
    scripts_dir: "/var/www/html/{{ stack }}.0{{ stack_id }}{% if acsf_environment=='' %}live{% elif acsf_environment=='test'%}test{% elif acsf_environment=='dev'%}dev{% endif %}/scripts"

- name: What is the scripts_dir variable
  debug:
    msg: "scripts_dir is: {{ scripts_dir}}"

# Ex: g2sc.stanford.edu
# Found example of a site with a vhost, hard linking to images by non-vhost path.
- name: Set absolute vhost path from sites service
  set_fact:
    absolute_vhost_path_sites_service: "{{ vhost }}.stanford.edu"
  when: vhost is defined

# Ex: sites.stanford.edu/g2scd7
# Ex: people.stanford.edu/jbickar
- name: Set absolute non-vhost path from sites service
  set_fact:
    absolute_path_sites_service: "{{ sites_service }}.stanford.edu/{{ inventory_hostname }}"

# Ex: g2sc-dev.sites.stanford.edu
- name: Set absolute path for testing
  set_fact:
    absolute_path_testing: "{% if vhost is defined %}{{ vhost }}{% else %}{{ acsf_site_name }}{% endif %}-{{ acsf_environment }}.{{ sites_service }}.stanford.edu"

# Ex: g2sc.sites.stanford.edu
- name: Set absolute path for production pre-launch
  set_fact:
    absolute_path_prod: "{% if vhost is defined %}{{ vhost }}{% else %}{{ acsf_site_name }}{% endif %}.{{ sites_service }}.stanford.edu"

# Ex: g2sc.stanford.edu
- name: Set absolute path for production at launch
  set_fact:
    absolute_path_launch: "{% if vhost is defined %}{{ vhost }}{% else %}{{ acsf_site_name }}{% endif %}.stanford.edu"

# Ex: "g2sc-dev.sites.stanford.edu" if migrating to dev,
#     "g2sc.stanford.edu" if launch_tasks = "launch"
- name: Set new absolute path based on destination
  set_fact:
    new_absolute_path: "{% if launch_tasks == 'launch' %}{{ absolute_path_launch }}{% elif acsf_environment == '' %}{{ absolute_path_prod }}{% else %}{{ absolute_path_testing }}{% endif %}"

- name: Debug absolute path for site
  debug:
    msg: "Absolute path: {{ new_absolute_path }}"

# Ex: drush @acsf.dev.cardinald7.g2scd7
- name: Set drush alias
  set_fact:
    drush_alias: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}"
