---
# Ansible role for setting a number of variables (mostly paths and URLs).
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role is required for "change-paths", "css-injector", "setup-site",
#   and "upload-site".
#
# INPUTS:
#   ace_environment
#   ace_site_name
#   drush_environment
#   inventory_hostname
#   launch_tasks
#   site_prefix
#   stack
#   stack_id
#   vhost
#
# OUTPUTS:
#   absolute_path_launch
#   absolute_path_prod
#   absolute_path_sites_service
#   absolute_path_testing
#   absolute_vhost_path_sites_service
#   drush_alias
#   file_public_path
#   new_absolute_path
#   scripts_dir
#   sites_service
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# Ex. /var/www/html/cardinald7.02live/scripts
# Ex. /var/www/html/cardinald7.02test/scripts
# Ex. /var/www/html/cardinald7.02dev/scripts
- name: Set scripts_dir variable
  set_fact:
    scripts_dir: "/var/www/html/stanfordpro.{% if ace_environment=='' %}prod{% else %}{{ ace_environment }}{% endif %}/scripts"

- name: Set SAML Install Dir variable
  set_fact:
    saml_dir: "/var/www/html/stanfordpro.{% if ace_environment=='' %}prod{% else %}{{ ace_environment }}{% endif %}/simplesamlphp"

- name: What is the scripts_dir variable
  debug:
    msg: "scripts_dir is: {{ scripts_dir }}"
  when: print_debug_messages == "TRUE"

- name: What is the saml_dir variable
  debug:
    msg: "saml_dir is: {{ saml_dir }}"
  when: print_debug_messages == "TRUE"

  # eg: stanfordpro.dev
- name: Set remote_username
  set_fact:
    remote_username: "stanfordpro.{% if ace_environment=='' %}prod{% else %}{{ ace_environment }}{% endif %}"

- name: What is the remote_username variable
  debug:
    msg: "remote_username is: {{ remote_username }}"
  when: print_debug_messages == "TRUE"

# Ex. stanfordprodev.ssh.enterprise-g1.acquia-sites.com
- name: Set remote_hostname
  set_fact:
    remote_hostname: "stanfordpro{% if ace_environment=='' %}{% elif ace_environment=='test' %}stg{% elif ace_environment=='dev' %}dev{% endif %}.ssh.prod.acquia-sites.com"

- name: What is the remote_hostname variable
  debug:
    msg: "remote_hostname is: {{ remote_hostname }}"
  when: print_debug_messages == "TRUE"


# Ex: g2sc.stanford.edu
# Found example of a site with a vhost, hard linking to images by non-vhost path.
- name: Set absolute vhost path from sites service
  set_fact:
    absolute_vhost_path_sites_service: "{{ vhost }}.stanford.edu"
  when: vhost is defined

# Ex: sites.stanford.edu/g2scd7
- name: Set absolute non-vhost path from sites service
  set_fact:
    absolute_path_sites_service: "sites.stanford.edu/{{ inventory_hostname }}"

# Ex: g2sc-dev.sites-pro.stanford.edu
- name: Set absolute path for testing
  set_fact:
    absolute_path_testing: "{% if vhost is defined %}{{ vhost }}{% else %}{{ inventory_hostname }}{% endif %}-{{ ace_environment }}.sites-pro.stanford.edu"

# Ex: g2sc.sites-pro.stanford.edu
- name: Set absolute path for production pre-launch
  set_fact:
    absolute_path_prod: "{% if vhost is defined %}{{ vhost }}{% else %}{{ inventory_hostname }}{% endif %}.sites-pro.stanford.edu"

# Ex: g2sc.stanford.edu
- name: Set absolute path for production at launch
  set_fact:
    absolute_path_launch: "{% if vhost is defined %}{{ vhost }}{% else %}{{ inventory_hostname }}{% endif %}.stanford.edu"

# Ex: "g2sc-dev.sites.stanford.edu" if migrating to dev,
#     "g2sc.stanford.edu" if launch_tasks = "launch"
- name: Set new absolute path based on destination
  set_fact:
    new_absolute_path: "{% if launch_tasks == 'launch' %}{{ absolute_path_launch }}{% elif ace_environment == '' %}{{ absolute_path_prod }}{% else %}{{ absolute_path_testing }}{% endif %}"

- name: Debug absolute path for site
  debug:
    msg: "Absolute path: {{ new_absolute_path }}"
  when: print_debug_messages == "TRUE"

# Ex: drush @acsf.dev.cardinald7.g2scd7
- name: Set drush alias
  set_fact:
    drush_alias: "drush @stanfordpro{{ drush_environment }}.{{ inventory_hostname }}"

# Certs dir.
- name: Set certs_dir path
  set_fact:
    certs_dir: /var/www/html/stanfordpro{{ drush_environment }}/simplesamlphp/cert/

- name: Debug certs_dir
  debug:
    msg: "Stanford SSP Certs Directory: {{ certs_dir }}"
  when: print_debug_messages == "TRUE"
