---
# Ansible role for identifying PHP in a database.
# https://github.com/SU-SWS/ansible-playbooks
# ===============================================
#
# The purpose of this role is to run a TASK, in this case, search for evidence
# of PHP in a database.  Upon finding what might be PHP, this role should
# abort migration of the host and save the PHP to our ansible.log file for
# review later.
#
# INPUTS:
#   inventory_hostname
#
# OUTPUTS:
#   database_php_candidates
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Check for PHP in database
  shell: "grep -o '.\\{0,20\\}{{ item }}{% if item in php_callbacks %}{{ parens }}{% endif %}.\\{0,20\\}' /tmp/{{ inventory_hostname }}/dbdump.sql; test $? -eq 1"
  register: database_php_candidates
  ignore_errors: yes
  with_items:
    - "{{ php_syntax }}"
    - "{{ php_callbacks }}"

- name: Prompt for action on databases with PHP
  pause:
    prompt: "Do you want to fail hosts with PHP candidates in their databases or continue their migration? (Options: fail, continue)"
  when: database_php_candidates|failed and php_candidates_consequence == "prompt"
  register: php_candidates_consequence_prompted

- name: Save PHP in file
  copy:
    content: "{{ inventory_hostname }} {{ database_php_candidates | json_query('results[*].stdout_lines') }}"
    dest: "/tmp/ansible.log"
  when: database_php_candidates|failed
  failed_when: php_candidates_consequence == "fail" or php_candidates_consequence_prompted.user_input == "fail"
