---
# Ansible role for changing paths after a site has been uploaded.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role runs a number of tasks to transform the database in such a way that
# images and absolute paths will work in the new ACSF environment. If any part
# of this role fails for a site, start from the top with a fresh download of
# the site.
#
# INPUTS:
#   absolute_path_sites_service
#   absolute_vhost_path_sites_service
#   acsf_site_name
#   drush_alias
#   inventory_hostname
#   link_attributes
#   new_absolute_path
#   protocols
#   sar_fulltext_commands
#   sarl_commands
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

##############################################################################
# Database surgery: Find and replace anything that the user may have entered #
# that references the old site.                                              #
# See https://stanfordits.atlassian.net/browse/SITES-248 for details.        #
#                                                                            #
# Text fields should replace http(s)://people.stanford.edu/sunetid with      #
# https://sunetid(-env).sites.stanford.edu. This will need to be     #
# changed when/if we decide on a URL syntax for people sites. Also, we are   #
# using {{ acsf_site_name }} here because we can rely on it being the same   #
# as the person's SUNetID due to validation rules for SUNetIDs.              #
#                                                                            #
# Text fields should replace http(s)://sites.stanford.edu/sitename with      #
# https://(acsf_site_name|vhost)(-env).sites.stanford.edu.           #
##############################################################################

# See discussion in https://github.com/SU-SWS/ansible-playbooks/pull/17
# And https://github.com/SU-SWS/ansible-playbooks/pull/22
# Ex: drush sar -y 'https://sites.stanford.edu/g2scd7/' 'https://g2sc-dev.sites.stanford.edu/'
- name: Update full paths in text
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ absolute_path_sites_service }}/' 'https://{{ new_absolute_path }}/'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes

# We are purposefully excluding sar from this because we can't assume that all
# absolute URLs should be relative.
# Also, "with_nested" will loop through all iterations of both arrays, as in:
# sarl/http, sarl/https, sarm/http, sarm/https.
# Ex: drush sarl -y https://sites.stanford.edu/g2scd7/' ''
- name: Remove absolute paths for links and menus
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ absolute_path_sites_service }}/' ''"
  with_nested:
    - "{{ sarl_commands }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes
  when: run_sarl == "TRUE"

# Note: I don't think this will ever get run, because we've already replaced
# https://sites.stanford.edu/g2scd7/ with https://g2sc.sites.stanford.edu/
# These are separated out because we are only using sar (not sarl or sarm) to do
# a string replacement of 'src="https://sites.stanford.edu/sitename/' with 'src="/'
# Ex: drush sar -y 'src="https://sites.stanford.edu/g2scd7/' 'src="/'
- name: Remove absolute paths for href, src, and url attributes
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ item[2] }}{{ absolute_path_sites_service }}/' '{{ item[1] }}/'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ link_attributes }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes

# Have to run these again for links that might include vhosts
# Ex: drush sar -y 'https://g2sc.stanford.edu/' 'https://g2sc-dev.sites.stanford.edu/'
- name: Update full vhost paths in text
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ absolute_vhost_path_sites_service }}/' '{{ item[1] }}{{ new_absolute_path }}/'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ protocols }}"
  when: vhost is defined
  notify: Clear site cache
  ignore_errors: yes

# Exclude sar from this
# Ex. drush sarl -y 'https://g2sc.stanford.edu/' ''
- name: Remove absolute vhost paths for links and menus
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ absolute_vhost_path_sites_service }}/' ''"
  with_nested:
    - "{{ sarl_commands }}"
    - "{{ protocols }}"
  when: vhost is defined
  notify: Clear site cache
  ignore_errors: yes
  when: run_sarl == "TRUE"

# Note: I don't think we ever get to this either, because we've already replaced
# https://g2sc.stanford.edu/ with https://g2sc.sites.stanford.edu/
# These are separated out because we are only using sar (not sarl or sarm) to do
# a string replacement of 'src="https://vhost.stanford.edu/' with 'src="/'
# Ex. drush sar -y 'src="https://g2sc.stanford.edu/' 'src="/'
- name: Remove absolute vhost paths for href, src, and url attributes
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ item[2] }}{{ absolute_vhost_path_sites_service }}/' '{{ item[1] }}/'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ link_attributes }}"
    - "{{ protocols }}"
  when: vhost is defined
  notify: Clear site cache
  ignore_errors: yes

# One more for things like src="/methane..."
# We only do this if the vhost is defined, because of the edge case where
# inventory_hostname also is a legitimate path for an href, like if the shortname
# is something like "books" and they have a path like
# "https://mysite.stanford.edu/books/my-awesome-book-title"
# Ex. drush sar -y 'src="/g2scd7/' 'src="/'
- name: Remove relative paths for href, src, and url attributes
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}/{{ inventory_hostname }}/' '{{ item[1] }}/'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ link_attributes }}"
  when: vhost is not defined
  notify: Clear site cache
  ignore_errors: yes

##############################################################################
# Database surgery: Find and replace references to sites/default/files with  #
# the string that ACSF uses for the file_public_path variable. Do NOT do a   #
# global find and replace of the "sites/default/files" string, for users may #
# have linked to files on other websites. We are assuming all absolute       #
# paths have been replaced above by relative paths.                          #
# See https://stanfordits.atlassian.net/browse/SITES-248 for details.        #
##############################################################################

# We already did a global find/replace of vhost.stanford.edu with
# https://acsf_site_name.sites.stanford.edu, so we just need to find/replace the
# "s3/files" string with the ACSF file_public_path value. We probably don't need
# to loop through {{ protocols }} here (http and https), as we should have
# already handled that in "Update full paths in text" or "Update full vhost
# paths in text".
# Ex. drush sar -y 'src="https://wow.stanford.edu/s3/files' 'src="https://wow.sites.stanford.edu/sites/g/files/sbiybj5000986/f'
- name: Replace absolute /s3/files links with path to files directory
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ item[2] }}{{ new_absolute_path }}/s3/files' '{{ item[1] }}{{ item[2] }}{{ new_absolute_path }}/{{ file_public_path.stdout | replace(' ','') }}'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ link_attributes }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes

# Same here: we already replaced absolute references in href and src
# attributes, so we only need to replace the "s3/files" string
# with the ACSF file_public_path value.
# Ex. drush sar -y 'src="/s3/files' 'src="/sites/g/files/sbiybj5000986/f'
- name: Replace relative S3 paths with path to files directory
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}/s3/files' '{{ item[1] }}/{{ file_public_path.stdout | replace(' ','') }}'"
  with_nested:
    - "{{ sar_fulltext_commands }}"
    - "{{ link_attributes }}"
  notify: Clear site cache
  ignore_errors: yes

# TODO: Do we need to do this for private files?

# Due to interactions between the S3FS module and the Insert module, it's
# possible for there to be direct links to the S3 bucket. Replace those
# sitewide. See https://www.drupal.org/node/2663674.
# This is a unique string, so we can just do a blanket replacement sitewide
# (e.g., with sar, sarl, sarm, sarv, sarjs).
# Ex. drush sar -y 'https://files-wow-stanford-edu.s3-us-west-2.amazonaws.com/s3fs-public' 'https://wow.sites.stanford.edu/sites/g/files/sbiybj5000986/f'
- name: Replace absolute S3 bucket links with path to files directory
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}{{ s3_bucket }}.s3-us-west-2.amazonaws.com/s3fs-public' 'https://{{ new_absolute_path }}/{{ file_public_path.stdout | replace(' ','') }}'"
  with_nested:
    - "{{ all_sar_commands }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes

# Same as above, but for different S3 syntax
# Ex. drush sar -y 'https://files-wow-stanford-edu.s3-us-west-2.amazonaws.com/s3fs-public' 'https://wow.sites.stanford.edu/sites/g/files/sbiybj5000986/f'
- name: Replace absolute S3 bucket links of a different syntax with path to files directory
  shell: "{{ drush_alias }} {{ item[0] }} -y '{{ item[1] }}s3-us-west-2.amazonaws.com/{{ s3_bucket }}/s3fs-public' 'https://{{ new_absolute_path }}/{{ file_public_path.stdout | replace(' ','') }}'"
  with_nested:
    - "{{ all_sar_commands }}"
    - "{{ protocols }}"
  notify: Clear site cache
  ignore_errors: yes

# We already replaced absolute references in menus and links
# attributes, so we only need to replace relative references to
# the "sites/default/files" string with the ACSF file_public_path value.
# The --regex option limits replacement to only those fields that match the
# regular expression.
- name: Replace link and menu items with new files path
  shell: "{{ drush_alias }} {{ item[0] }} -y --regex='^s3/files' '{{ file_public_path.stdout | replace(' ','') }}'"
  with_together:
    - "{{ sarl_commands }}"
  notify: Clear site cache
  ignore_errors: yes

# Ex. drush @acsf.test.cardinald7.eao scr /var/www/html/cardinald7.02test/scripts/js-injector.php
- name: Save modified JS Injector rules to disk
  shell: "{{ drush_alias }} scr {{ scripts_dir }}/js-injector.php"
  notify: Clear site cache

# Ex. drush @acsf.test.cardinald7.eao scr /var/www/html/cardinald7.02test/scripts/admin-shortcuts.php
- name: Hide reports menu links from admin shortcuts
  shell: "{{ drush_alias }} scr {{ scripts_dir }}/admin-shortcuts.php"
  notify: Clear site cache
  when: disable_top_reports_menu_items == "TRUE"
