---
# Ansible role for downloading the database and files from Sites.
# https://github.com/SU-SWS/ansible-playbooks
# ===============================================================
#
# This role saves a copy of the site database and files from Sites to your
# local directory in /tmp. I would call this a TASK role, since we don't know
# what state your directory and files might be in. But they should exactly
# match what's on Sites.
#
# INPUTS:
#   inventory_hostname
#   server_alias
#   site_prefix
#   sunetid
#   server
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Copy files to /tmp
  shell: "rsync -avz {{ playbook_dir }}/../{{ inventory_hostname }}/files/* /tmp/{{ inventory_hostname }}/files/"

- name: Copy database dump to /tmp
  shell: "rsync -avz {{ playbook_dir }}/../{{ inventory_hostname }}/dbdump.sql /tmp/{{ inventory_hostname }}/"

