---
# Ansible role for downloading the database and files from Sites.
# https://github.com/SU-SWS/ansible-playbooks
# ===============================================================
#
# This role saves a copy of the site database and files from Sites to your
# local directory in /tmp. I would call this a TASK role, since we don't know
# what state your directory and files might be in. But they should exactly
# match what's on Sites.
#
# INPUTS:
#   inventory_hostname
#   server_alias
#   site_prefix
#   sunetid
#   server
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Set Anchorage drush alias
  set_fact:
    anchorage_drush_alias: 'anc.{{ inventory_hostname }}'

- name: Get S3 bucket name
  shell: "drush @{{ anchorage_drush_alias }} -y --exact vget s3fs_bucket"
  register: s3_bucket

# Per internal conversation, John and Shea decided that it was a risk tradeoff
# to put the site in maintenance mode *before* making the database dump vs.
# *after*. See conversation in https://github.com/SU-SWS/ansible-playbooks/pull/72
# If this causes problems in the future, blame jbickar.
- name: Put Sites 1.x site in maintenance mode for final pre-launch migration
  shell: "drush @{{ anchorage_drush_alias }} -y --exact vset maintenance_mode 1"
  when:
    enable_maintenance_mode_source == "TRUE"

- name: Download copy of database from Anchorage
  shell: "drush @{{ anchorage_drush_alias }} sql-dump --structure-tables-key=common > /tmp/{{ inventory_hostname }}/dbdump.sql"

- name: Copy files from S3 to local
  shell: "aws --profile anchorage s3 sync s3://{{ s3_bucket }}/ /tmp/{{ inventory_hostname }}/files/"
