---
# Ansible role for checking whether a site is in the Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ===========================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state
# in which acsf_site_name and existing_sites have values.
#
# INPUTS:
#   inventory_hostname
#   prod_sites
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Fail if on list of protected prod sites
  fail:
    msg: "{{ inventory_hostname }} appears to be on our list of protected production sites."
  when: inventory_hostname in prod_sites
# Only fail for production environment
