---
# Ansible role for checking whether a site is in the Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ===========================================================
#
# The purpose of this role is to instantiate a STATE, in this case the state
# in which acsf_site_name and existing_sites have values.
#
# INPUTS:
#   absolute_vhost_path_sites_service
#   acsf_site_name
#   acsf_environment
#   inventory_hostname
#   prod_sites
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Fail if host is on list of protected prod sites
  fail:
    msg: "{{ inventory_hostname }} appears to be on our list of protected production sites."
  # Only fail for production environment
  when: inventory_hostname in prod_sites and ace_environment == ""

- name: Fail if inventory_hostname conflicts with prod sites
  fail:
    msg: "{{ inventory_hostname }} conflicts with an inventory hostname on our list of protected production sites."
  # Only fail for production environment
  when: inventory_hostname in prod_sites and ace_environment == ""

- name: Look up DNS for vhost
  shell: "dig +short {{ absolute_vhost_path_sites_service }}"
  register: dig_output

- name: Debug dns_lookup variable
  debug:
    msg: "DNS lookup is: {{ dig_output.stdout_lines }}"
  when:
    print_debug_messages == "TRUE"

# If DNS for <hostname>.stanford.edu already is pointed to ACSF (i.e., the
# results of "dig" return "*.cardinalsites.acsitefactory.com"), then fail.
# This protects production sites from being wiped out.
# See https://stanfordits.atlassian.net/browse/SITES-734.
- name: Fail if DNS for hostname is already on ACSF
  fail:
    msg: "{{ absolute_vhost_path_sites_service }} is already pointed to ACSF. You cannot migrate over a production site."
  when: dig_output.stdout is search("cardinalsites.acsitefactory.com") and ace_environment == ""

# If DNS for <hostname>.stanford.edu already is pointed to ACE (i.e., the
# results of "dig" return "hs-mrc-prod.stanford.edu"), then fail.
# This protects production sites from being wiped out.
# See https://stanfordits.atlassian.net/browse/SITES-734.
- name: Fail if DNS for hostname is already on ACE
  fail:
    msg: "{{ absolute_vhost_path_sites_service }} is already pointed to ACE. You cannot migrate over a production site."
  when: dig_output.stdout is search("sites-pro.stanford.edu") and ace_environment == ""
