---
# Ansible role for setting a the file_public_path variable.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# This role is required for the "css-injector" and "upload-site" roles.
#
# INPUTS:
#   drush_alias
#
# OUTPUTS:
#   file_public_path
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --
- name: Get public files directory
  shell: "{{ drush_alias }} status --fields='File directory path' --field-labels=0 --strict=0"
  register: file_public_path

- name: Be sure response does not go to default
  fail:
    msg: "Public file path cannot be default."
  when: file_public_path.stdout is search('sites/default/files')

- name: Print file_public_path
  debug:
    msg: "File public path: {{ file_public_path.stdout }}"
  when: print_debug_messages == "TRUE"

- name: Be sure response does not include drush warnings
  fail:
    msg: "There appear to be drush warning messages cluttering the file_public_path variable"
  when: file_public_path.stdout is search('The following module is missing')
