---
all_sar_commands:
  - sar
  - sarl
  - sarm
  - sarv
  - sarjs
sarl_commands:
  - sarl
  - sarm
sar_fulltext_commands:
  - sar
  - sarv
  - sarjs
protocols:
  - https://
  - http://
link_attributes:
  - href="
  - src="
  - url="
  # Quote single quotes. See https://stackoverflow.com/a/1315213.
  - href='\''
  - src='\''
  - url='\''
s3_file_prefixes:
  - s3/files
  - https://{{ s3_bucket }}.s3-us-west-2.amazonaws.com
