---
# Ansible playbook that recreates in Enterprise sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will sync a site from the Stanford Sites legacy hosting platform
# to its destination on ACSF.
#
# Can be run with: ansible-playbook -i inventory/sites migration-sync-only-playbook.yml
#
# SEE ALSO:
#
# full-migration-playbook.yml to create a new site on ACSF and sync from the
# existing infrastructure.
#
# acsf-site-setup-playbook.yml to only run the roles that set up the site on
# ACSF.
#
# add-vhost-playbook.yml if you wish only to add a vhost as a custom domain.
#
# post-db-restore-playbook.yml to only run the tasks that happen after the ACSF
# site has been restored from the database dump.
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Migrate sites from SWS infrastructure to Enterprise
# =============================================================
- hosts: ace,dev,test,prod,ode1,ode2,ode3,ode4,ode5
  connection: local

  vars_files:
    - ../migration_vars.yml
    - ../server_vars.yml
    - ../group_vars/all.yml
    - ../group_vars/ace.yml
    - ../ansible-sync/prod-sites.yml

  roles:
    - { role: roles/setup-local }
    - { role: roles/download-site }
    - { role: roles/css-injector }
    - { role: roles/upload-site }
    - { role: roles/post-db-restore }
    - { role: roles/change-paths }
    - { role: roles/ace-optimizations }
    - { role: roles/add-vhost }
    - { role: roles/cleanup-local }
  serial: 3
  max_fail_percentage: 100
