---
# Ansible playbook that recreates in Enterprise sites on our infrastructure.
# https://github.com/SU-SWS/ansible-playbooks
# ============================================================================
#
# This playbook will customize our servers on Acquia Cloud Enterprise with
# drush plugins and preferences that we define.
#
# Can be run with:
# ansible-playbook -i ansible-sync/servers.yml server-settings-playbook.yml
#
# KNOWN ISSUES:
# --
#
# PLAY 1: Set up server customizations
# ====================================
# - hosts: dev,test,prod
- hosts: ace,dev,test,prod,ra,ode1,ode2,ode3,ode4,ode5

  vars_files:
    - ../server_vars.yml

  roles:
    - roles/setup-server
