---
# Ansible role for uploading the database and files to Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role uploads the database and files from local to Site Factory. It also
# runs a number of tasks to transform the database in such a way that images
# and absolute paths will work in the new ACSF environment. If any part of this
# role fails for a site, restart from the tag "upload-site".
#
# INPUTS:
#   acsf_site_name
#   inventory_hostname
#   sitefactory_environment
#   drush_alias
#   drush_environment
#   stack
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# We sometimes have order-of-operation issues on drush updb.
# For instance, a "Column not found: 1054 Unknown column 'base.status' in
# 'field list'" error. Running "drush updb" twice allows us to get past that,
# and we can set ignore_updb_errors="true" in our inventory on a per-site
# basis.

- name: Drop database in Site Factory and install new database
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y sql-drop"
    - "sqlc < /tmp/{{ inventory_hostname }}/dbdump.sql"
    - "-y updb"
  ignore_errors: "{% if ignore_updb_errors == 'TRUE' %}yes{% endif %}"
  notify: Clear site cache

- name: Run drush updb a second time for recalcitrant sites
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y updb"
  when: ignore_updb_errors == "TRUE"

- name: Set site up as a Department site
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y vset install_profile stanford_dept"
    - "cc all"
    - "sqlq 'update system set status=\"1\" where name=\"stanford_dept\"'"
    - "-y en acsf"
    - "ev 'acsf_openid_allow_local_user_logins();'"
    - "rr"
  when: dept_site == "TRUE"
  notify: Clear site cache

- name: Do post-database-restore tasks
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y en acsf stanford_ssp paranoia"
    - "ev 'acsf_openid_allow_local_user_logins();'"
    - 'ev "_paranoia_remove_risky_permissions();"'
    - "-y dis stanford_afs_quota"
    # Must truncate this table otherwise users will lose roles in WMD->SSP upgrade path.
    - "sqlq 'truncate table webauth_roles_history'"
    - "sspwmd"
  notify: Clear site cache

- name: Post-database-restore tasks if not launch
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y en nobots"
    - "-y dis googleanalytics pingdom_rum"
  when: launch_tasks == ""
  notify: Clear site cache

# Copy public files first so that they exist and Drupal can find them if needed
- name: Copy public files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/ @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}:%files/ --exclude-paths=sites/default/files/js_injector/"
  notify: Clear site cache

# Copy private files first so that they exist and Drupal can find them if needed
- name: Copy private files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/private/ @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}:%private/"
  notify: Clear site cache
