---
# Ansible role for uploading the database and files to Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role uploads the database and files from local to Site Factory. It also
# runs a number of tasks to transform the database in such a way that images
# and absolute paths will work in the new ACSF environment. If any part of this
# role fails for a site, start from the top with a fresh download of the site.
#
# INPUTS:
#   acsf_site_name
#   inventory_hostname
#   sitefactory_environment
#   drush_alias
#   drush_environment
#   stack
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Drop database in Site Factory and install new database
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y sql-drop"
    - "sqlc < /tmp/{{ inventory_hostname }}/dbdump.sql"
  notify: Clear site cache

# BEANS BEANS BEANS,
# The change in the entity class can cause fatal errors and not allow the rest
# to continue. This is to ensure that all the parts are in the right place
# before we try to update.
- name: Run drush rr before running anything else
  shell: "{{ drush_alias }} {{ item }}"
  ignore_errors: yes
  with_items:
    - "-y rr"

# We sometimes have order-of-operation issues on drush updb. For instance, a
# "Column not found: 1054 Unknown column 'base.status' in 'field list'" error.
# To get past that, we can set ignore_updb_errors="TRUE" in our inventory on a
# per-site basis. That will allow us to move past errors in this task, and run
# "drush updb" a second time in the following task.
- name: Update database schema with drush updb
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y updb"
  ignore_errors: "{% if ignore_updb_errors == 'TRUE' %}yes{% endif %}"

# This only runs "drush rr" if ignore_updb_errors == "TRUE"
- name: Run drush rr before running drush updb a second time for recalcitrant sites
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y rr"
  when: ignore_updb_errors == "TRUE"
  ignore_errors: yes

# This only runs "drush updb" if ignore_updb_errors == "TRUE"
- name: Run drush updb a second time for recalcitrant sites
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y updb"
  when: ignore_updb_errors == "TRUE"
