---
# Ansible role for uploading the database and files to Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role uploads the database and files from local to Site Factory. It also
# runs a number of tasks to transform the database in such a way that images
# and absolute paths will work in the new ACSF environment. If any part of this
# role fails for a site, restart from the tag "upload-site".
#
# INPUTS:
#   acsf_site_name
#   inventory_hostname
#   sitefactory_environment
#   drush_alias
#   drush_environment
#   stack
#
# OUTPUTS:
# --
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Drop database in Site Factory and install new database
  shell: "{{drush_alias }} {{ item }}"
  with_items:
    - "-y sql-drop"
    - "sqlc < /tmp/{{ inventory_hostname }}/dbdump.sql"
  notify: Clear site cache

# We sometimes have order-of-operation issues on drush updb. For instance, a
# "Column not found: 1054 Unknown column 'base.status' in 'field list'" error.
# To get past that, we can set ignore_updb_errors="TRUE" in our inventory on a
# per-site basis. That will allow us to move past errors in this task, and run
# "drush updb" a second time in the following task.
- name: Update database schema with drush updb
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y updb"
  ignore_errors: "{% if ignore_updb_errors == 'TRUE' %}yes{% endif %}"

# This only runs "drush rr" if ignore_updb_errors == "TRUE"
- name: Run drush rr before running drush updb a second time for recalcitrant sites
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y rr"
  when: ignore_updb_errors == "TRUE"
  ignore_errors: yes

# This only runs "drush updb" if ignore_updb_errors == "TRUE"
- name: Run drush updb a second time for recalcitrant sites
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y updb"
  when: ignore_updb_errors == "TRUE"

# Set the install profile by looking for the enabled supporting module.
# Order of operations is important here, because a JSA site may have BOTH
# "stanford_jumpstart" and "stanford_jumpstart_academic" enabled, yet we want
# to be sure to set "install_profile" to "stanford_sites_jumpstart_academic" for
# JSA sites (so that they get all the correct code).
- name: Find and set the install profile by helper modules.
  shell: "FOUND=$({{ drush_alias }} php-eval \"var_dump(module_exists('{{ item.module }}'));\"); if [[ \"$FOUND\" =~ 'true' ]]; then {{ drush_alias }} -y vset install_profile '{{ item.profile }}'; fi;"
  with_items:
    - { module: 'stanford_jumpstart', profile: 'stanford_sites_jumpstart' }
    - { module: 'stanford_jumpstart_plus', profile: 'stanford_sites_jumpstart_plus' }
    - { module: 'stanford_jumpstart_academic', profile: 'stanford_sites_jumpstart_academic' }
    - { module: 'stanford_jumpstart_vpsa', profile: 'stanford_jumpstart_vpsa' }
    - { module: 'stanford_jumpstart_lab', profile: 'stanford_sites_jumpstart_lab' }
    - { module: 'stanford_jumpstart_engineering', profile: 'stanford_sites_jumpstart_engineering' }
  when: product_site == "TRUE"

- name: Set site up as a Department site
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y vset install_profile stanford_dept"
    - "cc all"
    - "sqlq 'update system set status=\"1\" where name=\"stanford_dept\"'"
    - "-y en acsf"
    - "rr"
  when: dept_site == "TRUE"
  notify: Clear site cache

- name: Do post-database-restore tasks
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y en acsf acsf_helper stanford_ssp paranoia"
    - 'ev "_paranoia_remove_risky_permissions();"'
    - "-y vset sws_migration_version {{ migration_version }}"
    - "-y dis stanford_afs_quota acsf_openid openid mollom xmlrpc statistics"
    - "-y pm-uninstall stanford_afs_quota acsf_openid mollom xmlrpc statistics"
    - "-y pm-uninstall openid"
    # Must truncate this table otherwise users will lose roles in WMD->SSP upgrade path.
    - "sqlq 'truncate table webauth_roles_history'"
    - "sspwmd"
  notify: Clear site cache

- name: Post-database-restore tasks if not launch
  shell: "{{ drush_alias }} {{ item }}"
  with_items:
    - "-y en nobots"
    - "-y dis googleanalytics pingdom_rum"
  when: launch_tasks == ""
  notify: Clear site cache

# Copy public files first so that they exist and Drupal can find them if needed
- name: Copy public files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/ @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}:%files/ --exclude-paths=sites/default/files/js_injector/"
  notify: Clear site cache

# Copy private files first so that they exist and Drupal can find them if needed
- name: Copy private files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/private/ @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}:%private/"
  notify: Clear site cache
