---
# Ansible role for uploading the database and files to Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# ==================================================================
#
# This role uploads the database and files from local to Site Factory. It also
# runs a number of tasks to transform the database in such a way that images
# and absolute paths will work in the new ACSF environment. If any part of this
# role fails for a site, restart from the tag "upload-site".
#
# INPUTS:
#   acsf_site_name
#   inventory_hostname
#   sitefactory_environment
#   drush_environment
#   server_alias
#   site_prefix
#   stack
#   server
#   dept_site
#   wait_time
#
# OUTPUTS:
#   files_public_path
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Drop database in Site Factory and install new database
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "-y sql-drop"
    - "sqlc < /tmp/{{ inventory_hostname }}/dbdump.sql"
  notify: Clear site cache

- name: Set site up as a Department site
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "-y vset install_profile stanford_dept"
    - "cc all"
    - "sqlq 'update system set status=\"1\" where name=\"stanford_dept\"'"
    - "-y en acsf"
    - "ev 'acsf_openid_allow_local_user_logins();'"
    - "rr"
  when: dept_site == "TRUE"
  notify: Clear site cache

- name: Do post-database-restore tasks
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "-y updb"
    - "-y en acsf nobots stanford_ssp"
    - "-y dis googleanalytics pingdom_rum"
    - "sqlq 'truncate table webauth_roles_history'"
    - "sspwmd"
  notify: Clear site cache

- name: Find any absolute paths and replace them - people sites
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "sar -y 'http://people.stanford.edu/{{ inventory_hostname }}/' '/'"
    - "sar -y 'https://people.stanford.edu/{{ inventory_hostname }}/' '/'"
    - "sarm -y 'http://people.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarm -y 'https://people.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarl -y 'http://people.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarl -y 'https://people.stanford.edu/{{ inventory_hostname }}/' ''"
  when:
    site_prefix == "dp"
  notify: Clear site cache

- name: Find any absolute paths and replace them - group and dept sites
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "sar -y 'http://sites.stanford.edu/{{ inventory_hostname }}/' '/'"
    - "sar -y 'https://sites.stanford.edu/{{ inventory_hostname }}/' '/'"
    - "sarm -y 'http://sites.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarm -y 'https://sites.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarl -y 'http://sites.stanford.edu/{{ inventory_hostname }}/' ''"
    - "sarl -y 'https://sites.stanford.edu/{{ inventory_hostname }}/' ''"
  when:
    site_prefix == "ds"
  notify: Clear site cache

- name: Find any relative paths and replace them
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "sar -y 'href=\"/{{ inventory_hostname }}/' 'href=\"/'"
    - "sar -y 'src=\"/{{ inventory_hostname }}/' 'src=\"/'"
    - "sarm -y 'href=\"/{{ inventory_hostname }}/' 'href=\"/'"
    - "sarm -y 'src=\"/{{ inventory_hostname }}/' 'src=\"/'"
    - "sarl -y 'href=\"/{{ inventory_hostname }}/' 'href=\"/'"
    - "sarl -y 'src=\"/{{ inventory_hostname }}/' 'src=\"/'"
  notify: Clear site cache

- name: Find any vhost absolute paths and replace them
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} {{ item }}"
  with_items:
    - "sar -y 'http://{{ vhost }}.stanford.edu/' '/'"
    - "sar -y 'https://{{ vhost }}.stanford.edu/' '/'"
    - "sarm -y 'http://{{ vhost }}.stanford.edu/' ''"
    - "sarm -y 'https://{{ vhost }}.stanford.edu/' ''"
    - "sarl -y 'http://{{ vhost }}.stanford.edu/' ''"
    - "sarl -y 'https://{{ vhost }}.stanford.edu/' ''"
  when:
    vhost is defined
  notify: Clear site cache

- name: Get public files directory
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} status --fields='File directory path' --field-labels=0 --strict=0"
  register: file_public_path

- name: Print file_public_path
  debug:
    msg: "File public path: {{ file_public_path.stdout }}"

- name: Be sure response does not include drush warnings
  fail:
    msg: "There appear to be drush warning messages cluttering the file_public_path variable"
  when: file_public_path.stdout | search('The following module is missing')

- name: Replace sites/default/files with path to files directory
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} sar -y 'http://{{ vhost }}.stanford.edu/sites/default/files' 'https://{{ vhost }}.stanford.edu/{{ file_public_path.stdout | replace(' ','') }}'"
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} sar -y 'https://{{ vhost }}.stanford.edu/sites/default/files' 'https://{{ vhost }}.stanford.edu/{{ file_public_path.stdout | replace(' ','') }}'"
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} sar -y 'href=\"/sites/default/files' 'href=\"/{{ file_public_path.stdout | replace(' ','') }}'"
  shell: "drush @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }} sar -y 'src=\"/sites/default/files' 'src=\"/{{ file_public_path.stdout | replace(' ','') }}'"
  notify: Clear site cache

- name: Copy files from local to Site Factory
  shell: "drush -y rsync /tmp/{{ inventory_hostname }}/files/ @acsf{{ drush_environment }}.{{ stack }}.{{ acsf_site_name }}:%files/"
  notify: Clear site cache
