---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a site in Site Factory.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   ace_site_name
#   drush_alias
#   existing_sites
#   group_ids
#   inventory_hostname
#   profile
#   site_environment
#   sites_formatted
#   stack_id
#   wait_time
#
# OUTPUTS:
#   bootstrap_status
#   site_created
#   site_exists
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

# TODO: CREATE DATABASE
