---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a site in Site Factory.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   acsf_site_name
#   drush_alias
#   existing_sites
#   group_ids
#   inventory_hostname
#   profile
#   sitefactory_environment
#   sites_formatted
#   stack_id
#   wait_time
#
# OUTPUTS:
#   bootstrap_status
#   site_created
#   site_exists
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Set site_exists to TRUE if it exists
  set_fact:
    site_exists: TRUE
  when: site_id|length > 0

- name: debug
  debug:
    var: site_exists
  when: print_debug_messages == "TRUE"

- name: Create new site on Site Factory
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/sites"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body:
      site_name: "{{ acsf_site_name }}"
      install_profile: "{{ profile }}"
      codebase: "{{ stack_id }}"
      group_ids: "{{ group_ids }}"
    force_basic_auth: yes
    body_format: json
    return_content: yes
  register: site_created
  when: site_exists == "FALSE"

- pause:
    minutes: 1

- name: Re-call the sites-json stuff
  include_role:
    name: sites-json
  when: site_exists == "FALSE"

- name: Check that site is available
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/sites/{{ site_id }}"
    method: GET
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    force_basic_auth: yes
    body_format: json
    return_content: yes
  retries: "{{ wait_time }}"
  delay: 50
  register: site_created
  until: site_created is not failed
  when: site_exists == "FALSE"
