---
# Ansible role for creating a site on Site Factory
# https://github.com/SU-SWS/drupal-caravan
# ================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a site in Site Factory.
#
# INPUTS:
#   inventory_hostname
#   sitefactory_environment
#   profile
#   group_ids
#   stack_id
#   acquia_username
#   acquia_api_key
#
# OUTPUTS:
#   existing_sites
#   site_created
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Check if site is installed on Site Factory
  shell: "drush @{{ drush_alias_environment }}.{{ stack }}.{{ inventory_hostname }} status --fields='Drupal bootstrap' --field-labels=0"
  register: bootstrap_successful

- name: Bootstrap status
  debug:
    msg: "{{ bootstrap_successful | json_query('stdout') }}"

- name: Create new site on Site Factory
  uri:
    url: "https://www.{{ sitefactory_environment }}.acsitefactory.com/api/v1/sites"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body:
      site_name: "{{ inventory_hostname }}"
      install_profile: "{{ profile }}"
      codebase: "{{ stack_id }}"
      group_ids: 126
    force_basic_auth: yes
    body_format: json
    return_content: yes
  register: site_created
  when: bootstrap_successful | json_query('stdout') is not defined

- name: Wait for site to install
  shell: "drush @{{ drush_alias_environment }}.{{ stack }}.{{ inventory_hostname }} status --fields='Drupal bootstrap' --field-labels=0"
  async: 360
  poll: 0
  register: async_play
  when: bootstrap_successful | json_query('stdout') is not defined

- name: Check install results
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: async_jobs
  until: async_jobs.finished
  with_items:
    - "{{ async_play }}"
  retries: 10
  delay: 5
  when: bootstrap_successful | json_query('stdout') is not defined

- debug: msg="{{ bootstrap_successful | json_query('stdout') }} or {{ async_jobs | json_query('results[*].stdout') }}"

- name: Fail the play if result was not success
  fail: msg="Not able to grab a value for Drupal Bootstrap, which suggests your site may not be setup in ACSF."
  when: "' Successful ' not in bootstrap_successful | json_query('stdout') and
        ' Successful ' not in async_jobs | json_query('results[*].stdout')"
