---
# Ansible role for creating a site on Site Factory.
# https://github.com/SU-SWS/ansible-playbooks
# =================================================
#
# The purpose of this role is to instantiate a STATE, in this case the
# existence of a site in Site Factory.
#
# INPUTS:
#   acquia_api_key
#   acquia_username
#   acsf_site_name
#   drush_alias
#   existing_sites
#   group_ids
#   inventory_hostname
#   profile
#   sitefactory_environment
#   sites_formatted
#   stack_id
#   wait_time
#
# OUTPUTS:
#   bootstrap_status
#   site_created
#
# ALTERNATIVE ROLES:
# --
#
# REQUIREMENTS:
# --
#
# KNOWN ISSUES:
# --

- name: Search for existing site
  set_fact:
    search_for_site: "{{ sites_formatted|json_query(the_query) }}"
  vars:
    the_query: "[?site=='{{ acsf_site_name }}']"

- name: Set site_exists to TRUE if it exists
  set_fact:
    site_exists: TRUE
  when: search_for_site|length > 0

- name: Set site_exists to FALSE if it does not exist
  set_fact:
    site_exists: FALSE
  when: search_for_site|length == 0

- name: debug
  debug:
    var: site_exists
  when: print_debug_messages == "TRUE"

- name: Create new site on Site Factory
  uri:
    url: "https://www.{{ sitefactory_environment }}cardinalsites.acsitefactory.com/api/v1/sites"
    method: POST
    user: "{{ acquia_username }}"
    password: "{{ acquia_api_key }}"
    body:
      site_name: "{{ acsf_site_name }}"
      install_profile: "{{ profile }}"
      codebase: "{{ stack_id }}"
      group_ids: "{{ group_ids }}"
    force_basic_auth: yes
    body_format: json
    return_content: yes
  register: site_created
  when: not site_exists

- pause:
    minutes: 1

- name: Check drush can bootstrap site
  shell: "{{ drush_alias }} status"
  retries: "{{ wait_time }}"
  delay: 50
  register: bootstrap_status
  until: bootstrap_status.stdout is search('Database name')

- name: Re-call the sites-json stuff
  include_role:
    name: get-sitename
  when: not site_exists
